import { APIClient } from "./Http";
export const AppointmentsKpiClient = new APIClient("/getAppointments");
export const CanceledMonthlyAppointmentsKpiClient = new APIClient("/getMonthlyCanceledAppointments");
export const MonthlyAppointmentsKpiClient = new APIClient("/getMonthlyAppointments");
export const TotalRevenueKpiClient = new APIClient("/getTotalRevenue");
export const PatientsDebtKpiClient = new APIClient("/fetchPayments");
export const CashierNumberKpiClient = new APIClient("/OnlyCashierNumber");
export const AppointmentKpiClient = new APIClient("/appointmentKpipeak");
export const TotalPatientKpiClient = new APIClient("/TotalPatients");
export const PatientsAgeGroupKpiClient = new APIClient("/calculateAgePercentage");
export const PatientsReferralClient = new APIClient("/countPatientsByReferral");
export const TotalcachierAmount = new APIClient("/retrieveFromCashier");
export const getCreanceApiClient = new APIClient("/getPaymentKpi");
export const CanceledAppointmentsKpiClient = new APIClient("/getCanceledAppointments");
export default AppointmentsKpiClient;
