import { APIClient } from "./Http";
export const xrayApiClient = new APIClient("StoreParaclinique");
export const updateParacliniqueApiClient = new APIClient("updateParaclinique");
export const fetchBloodTestOperation = new APIClient("fetchOperationBloodTests");
export const getOrdonanceIdApiClient = new APIClient("getOrdonanceId");
export const origonalxrayApiClient = new APIClient("xray");
export const categoryXrayApiClient = new APIClient("getxrayCategorys");
export const deleteCategoryApiClient = new APIClient("deleteCategory");
export const PatientXrayApiClient = new APIClient("showpatientxrays");
export const insertOpwithoutxray = new APIClient("insertWihtoutxray");
export const DeleteradioApiClient = new APIClient("deleteRadio");
export const deletebloodtestApiClient = new APIClient("deleteBloodTest");
export const deleteOrdonanceApiClient = new APIClient("deleteOrdonance");
export const xraysWithCategoryApiClient = new APIClient("getXrayPreferencesWithCategories");
export const NurseXrayvalidationApiClient = new APIClient("getXraysByOperation");
export const fetchxrayfirststep = new APIClient("fetchXrays");
/* new apis  */
export const getnoteApiClient = new APIClient("fetchNote");
export const editnoteApiclient = new APIClient("EditOpNote");
