import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { RouterProvider } from "react-router-dom";
import "./index.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import router from "./Routes.tsx";
import SnackBarComponentv2 from "./components/SnackBarComponentv2.tsx";
import ConfirmDialog from "./components/ConfirmDialog.tsx";
const queryClient = new QueryClient();
ReactDOM.createRoot(document.getElementById("root")).render(_jsxs(QueryClientProvider, { client: queryClient, children: [_jsxs(React.StrictMode, { children: [_jsx(RouterProvider, { router: router }), _jsx(ConfirmDialog, {}), _jsx(SnackBarComponentv2, {})] }), _jsx(ReactQueryDevtools, {})] }));
